version: '3.1'

networks:
  devenv-network-pedrojs:

services:
  redis:
    container_name: devenv_redis_pedrojs
    image: redis:6
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - devenv-network-pedrojs

  mysql:
    container_name: devenv_mysql_pedrojs
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /opt/dev/pedrojs/mysql_data:/var/lib/mysql
      - ./database/mysql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/mysql/table.sql:/docker-entrypoint-initdb.d/2_table.sql
    ports:
      - "3306:3306"
    networks:
      - devenv-network-pedrojs

  postgres:
    container_name: devenv_postgres_pedrojs
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /opt/dev/pedrojs/postgres_data:/var/lib/postgresql/data
      - ./database/postgres/database.sql:/docker-entrypoint-initdb.d/1_database.sql
      - ./database/postgres/table.sql:/docker-entrypoint-initdb.d/2_table.sql
    ports:
      - "5432:5432"
    networks:
      - devenv-network-pedrojs

  mongo:
    container_name: devenv_mongodb_pedrojs
    image: mongo:4.4.10
    command: --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    volumes:
      - /opt/dev/pedrojs/mongodb_data:/data/collection
      - ./database/mongodb/user.js:/docker-entrypoint-initdb.d/1_user.js
    ports:
      - "27017:27017"
    networks:
      - devenv-network-pedrojs

  mongo-express:
    container_name: devenv_mongo_express_pedrojs
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - devenv-network-pedrojs

  adminer:
    container_name: adminer_pedrojs
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - devenv-network-pedrojs
